name: sessions_repository
description: A repository managing the sessions domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  api_client:
    path: ../api_client
  objects:
    path: ../../api/packages/objects

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^10.0.0
