name: api_client
description: An client for a REST API.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  http: ^1.4.0
  web_socket_client: ^0.2.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
