name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  api_client:
    path: packages/api_client
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  web_socket_client: ^0.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  hydrated_bloc: ^10.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shadcn_flutter: ^0.0.39
  uuid: ^4.5.1
  recase: ^4.1.0
  sessions_repository:
    path: packages/sessions_repository
  objects:
    path: api/packages/objects

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
