name: objects
description: Shared objects for the API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
