name: api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  collection: ^1.19.1
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.2
  hydrated_bloc: ^9.1.5
  objects:
    path: packages/objects
  uuid: ^4.5.1

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
